### ISSUE TITLE
company-preview-if-just-one-frontend wrong number of arguments

### ISSUE THREAD

**Issue by TheJJ** [proofit404/company-anaconda#14]
With current `company-anaconda-20151210.323`, `company-20151229.2028`, `anaconda-mode-20150922.537` and this config:

``` lisp
(anaconda-mode)
(add-to-list 'company-backends 'company-anaconda)
(company-mode)
```

I get those errors:

```
eldoc error: (error 127.0.0.1%3anil/80 Name or service not known)
Company: An error occurred in post-command
Company: frontend company-preview-if-just-one-frontend error "Company: backend (company-anaconda) error "Wrong number of arguments: (1 . 2), 3" with args (pre-render issubclass nil)" on command post-command
```

No idea how to fix them, I have just updated the packages.

**Comment by wkevina** [comment]
I encountered this issue sometime yesterday, and you have already fixed it! Thanks for taking care of these issues so quickly.

**Comment by proofit404** [comment]
@wkevina I'm glad my projects are useful for others as well as for me.
