### ISSUE TITLE
Handing over to company-capf is essential

### ISSUE THREAD

**Issue by vspinu** [proofit404/company-anaconda#15]
This is related to #8. I am starting it nevertheless because I think there could be a simple solution for this. At least it could be one line in the readme on this.

As I pointed in my [anaconda reprot](https://github.com/proofit404/anaconda-mode/issues/161) handing completions to `python-shell-complete-at-point` is extremely useful. I even think it should be given priority over `anaconda` backend because it's much faster. 

Similarly to anaconda completion this could be fixed by either falling back on `python-complete-at-point` in `company-anaconda` or providing a setup for grouped backend with `python-complete-at-point`. The later could be simply stated in the installation instruction.

**Comment by proofit404** [comment]
This is only possible if `company-mode` can merge two asynchronous backends results.

**Comment by vspinu** [comment]
I just tried the grouped versions:

```
  (setq-local company-backends `((company-capf company-anaconda) ,@company-backends))
```

It doesn't work :(. `company-anaconda` is not getting the turn.

**Comment by proofit404** [comment]
As far as I can tell `company-capf` is synchronous backend.

**Comment by vspinu** [comment]
It seems to be so. Does it mean that it would be hard or impossible to merge one async and sync backends? 

You seem to have asked exactly same question [here](https://github.com/company-mode/company-mode/issues/62) a couple of years ago. That issue was tagged as resolved.

For now I am resorting for this quick fix:

```elisp

;; temporary fix for https://github.com/proofit404/company-anaconda/issues/15
(defun company-anaconda (command &optional arg &rest _args)
  "Anaconda backend for company-mode.
See `company-backends' for more info about COMMAND and ARG."
  (interactive (list 'interactive))
  (cl-case command
    (interactive (company-begin-backend 'company-anaconda))
    (prefix (company-anaconda-prefix))
    (candidates (let ((native-comps ))
                  (or (and (> (length arg) 0)
                           (funcall (nth 2 (python-completion-at-point)) arg nil t))
                      (cons :async
                            (lambda (callback)
                              (company-anaconda-candidates callback))))))
    (doc-buffer (company-anaconda-doc-buffer arg))
    (meta (company-anaconda-meta arg))
    (annotation (funcall company-anaconda-annotation-function arg))
    (location (company-anaconda-location arg))
    (ignore-case company-anaconda-case-insensitive)
    (sorted t)))
```

**Comment by proofit404** [comment]
What does `(length arg)` mean? Why do you bind `native-comps`?

**Comment by vspinu** [comment]
> (length arg) mean? 

`arg` is the prefix. For unclear reason if prefix is "" python.el completion gives a lot of crap. The prefix will be "" on objects references right after "." .  For example in `tt = {}; tt.|`  I am not sure if that is a generic enough fix but it worked well for me so far on object fields. 

But I am not getting function argument's completions. Like in 

```
def ttt(aaa = 23):
    pass

ttt(aa| 
```

Does jedi give completions in this case?


> Why do you bind native-comps?

Damn. That's a remnant which I forgot to delete. It's not needed. Updated the comment.

**Comment by proofit404** [comment]
I find the root of the problem.  Progress so far:
![company-anaconda-capf](https://cloud.githubusercontent.com/assets/1862725/13195882/612aed6c-d7ce-11e5-8555-8977b820cc1e.png)

**Comment by vspinu** [comment]
Great! Thanks for looking into it. 

I actually prefer the full prefix in the popup (with the symbol before the dot) as it disambiguates clearly that those are fields and method completions rather than some arbitrary global vars.

**Comment by proofit404** [comment]
Full prefix is the last todo for the `capf` branch.
