### ISSUE TITLE
"Doubled completions" on MELPA package

### ISSUE THREAD

**Issue by Purring** [proofit404/company-anaconda#17]
bug happens when:
* Company + company-anaconda are at latest
* There is an inf-python process running (does not happen wen there is no inf-python)

it almost seems like it's trying to be "smart" by trying to complete something that matches before the point when it shouldn't be doing that.

Hopefully these pictures explain it better than i can, but  basically anything that can autocomplete that is BEHIND something (garbage text, numbers, functions, classes, methods, etc) and has NO SPACES, it doubles the completion ` retu|[return]def reallylongfunctionname():` but `retu|[rn]<space>def reallylongfunctionname() ` is just fine.
completion on a method isn't doubled (eg `math.c[os]def reallylongfunctionname():`) but the initial math is (`mat|[math]def reallylongfunctionname():`

I'm on emacs 24.5.1, company is at latest version, and so is anaconda-mode and company anaconda.
![1](https://cloud.githubusercontent.com/assets/12635250/14064355/621e3ffa-f3ce-11e5-8b8e-d3293961a25f.png)
![2](https://cloud.githubusercontent.com/assets/12635250/14064356/62220da6-f3ce-11e5-8f6b-2ec8cfe3e05f.png)
![3](https://cloud.githubusercontent.com/assets/12635250/14064357/6225a9e8-f3ce-11e5-844a-3c8417b085d7.png)
![4](https://cloud.githubusercontent.com/assets/12635250/14064358/622cc6f6-f3ce-11e5-88e7-fa32fc25a47d.png)

**Comment by proofit404** [comment]
I haven't touched both `anaconda-mode` and `company-anaconda` for a while. Can you try to setup `company-mode` from git and check if this issue still persist?

**Comment by Purring** [comment]
It still happens with company(git)

**Comment by proofit404** [comment]
I try it all day but I can't reproduce your issue :(
![company-anaconda-bug](https://cloud.githubusercontent.com/assets/1862725/14081314/3012c55a-f51b-11e5-809c-fcf08998c868.png)

**Comment by Purring** [comment]
It only happens if you type BEFORE an already completed keyword
I'm sorry for explaining it wrong, hopefully this does it better. It's just a verry strange thing to try to explain for me.
![out](https://cloud.githubusercontent.com/assets/12635250/14088220/3c1c89c2-f4fc-11e5-89c8-16e631a9967e.gif)

**Comment by Purring** [comment]
For compairison, here is how company-mode(stable) + company-anaconda(stable) behave
![out](https://cloud.githubusercontent.com/assets/12635250/14089022/b3a0ff7e-f500-11e5-93cf-8132511ed0d9.gif)

**Comment by proofit404** [comment]
Confirmed.
![company-anaconda-repeated-bug](https://cloud.githubusercontent.com/assets/1862725/14138252/42675af0-f67d-11e5-85b5-063616e50d3e.png)
But I'm not sure it is a bug or desired behaviour.

**Comment by Purring** [comment]
I don't think it would be desired, since it didn't happen in old versions of company-anaconda and this is the only plugin i've found that has behavior like this. Looking through the code, i have a feeling it got introduced on one of the Feb 20th commits, but ill check them out once I'm home to confirm

**Comment by Purring** [comment]
Well, ive got some time to figure this out since it is now the weekend. It seems like this bug was introduced with [commit 099cb37](https://github.com/proofit404/company-anaconda/commit/099cb37319c3a91eca2337b91cb4613dc5ab4f7b) by adding company-capf features

I also did more tinkering and i found this bug also only happens with a running inf-python process, which furthers my theory that it has something to do with company-capf(since company-capf gets it's completions from the inf-python)

**Comment by Purring** [comment]
Any input on this? Im not too familiar with company's internals or jedi to really know what's going on behind the scenes.
A git revert for 0099cb37 does fix the problem, but im not entirely sure if that's a good thing or not.

**Comment by proofit404** [comment]
Maybe I will have time to look on this at the weekend.

**Comment by proofit404** [comment]
I start working on this bug in the `capf-bug` branch. But I won't give any estimates on release date.
