### ISSUE TITLE
No completions, but errors?

### ISSUE THREAD

**Issue by bastibe** [proofit404/company-anaconda#22]
I recently switched from elpy to anaconda-mode, but I can't get completions to work.

Whenever company tries to display completions, it just prints the following to the *Messages* buffer:

```
Company: An error occurred in post-command
Company: frontend company-pseudo-tooltip-unless-just-one-frontend error "Company: backend company-anaconda error "Wrong number of arguments: (1 . 2), 3" with args (pre-render M nil)" on command post-command
Skip anaconda-mode eldoc response
```

The `M` in the above output depends on the typed prefix. The above output is for the following source code:

```python
import re
re.m<cursor>
```

Here are my relevant init.el entries:

```elisp
(add-hook 'python-mode-hook 'anaconda-mode)
(add-hook 'python-mode-hook 'anaconda-eldoc-mode)
(eval-after-load "company"
  '(add-to-list 'company-backends 'company-anaconda))
```

I am using company-mode 0.9.0, anaconda-mode 0.1.2, and company-anaconda 0.1.0, freshly installed from melpa-stable.

**Comment by proofit404** [comment]
Eval `(setq debug-on-error t)` and post full traceback here.

**Comment by bastibe** [comment]
Here you go:

[traceback.txt](https://github.com/proofit404/company-anaconda/files/408953/traceback.txt)

**Comment by proofit404** [comment]
Please remove all `elc` files from elpa directory so traceback will contain actual source code (not byte code). Sorry I forgot about it.

**Comment by bastibe** [comment]
No problem, and thanks for your help:

[traceback.txt](https://github.com/proofit404/company-anaconda/files/408999/traceback.txt)

**Comment by proofit404** [comment]
You are using melpa stable and company-anaconda was tagged a while ago. Backend calling signature changed and I forgot make new release. This issue've been fixed in master. I push new tag right now. Your problem should be solved when melpa stable will finish its new build.

**Comment by bastibe** [comment]
Thank you very much for your help!
