### ISSUE TITLE
Company-anaconda try autocomplete literal binary integers

### ISSUE THREAD

**Issue by ryukinix** [proofit404/company-anaconda#26]
![image](https://user-images.githubusercontent.com/7642878/30000953-4c250cf0-9054-11e7-9eaf-92e8591b1bf7.png)

# How to reproduce

1. Create a Python empty file
2. Active company-mode with company-anaconda backend setup
3. Type any literal integer binary and expect or force autocomplete

# Expected Behavior

No autocomplete for this, because just doesn't makes sense.

**Comment by bet4it** [comment]
Solved by #33.

**Comment by ryukinix** [comment]
Tested, it was fixed. Thanks @bet4it
