### ISSUE TITLE
Melpe stable

### ISSUE THREAD

**Issue by nlamirault** [proofit404/company-anaconda#3]
could you please create a tag to use this package using melpa stable [1].
Thanks

[1] : http://stable.melpa.org/

**Comment by proofit404** [comment]
Actually this is possible only after anaconda-mode 0.2 release with tramp support. Currently I'm in progress solving this task.

**Comment by nlamirault** [comment]
OK Thanks

**Comment by nlamirault** [comment]
Any news ?

**Comment by proofit404** [comment]
First of all thanks for your patience.  Currently I work on this. You can see progress in the [feature/pypi](https://github.com/proofit404/anaconda-mode/tree/feature/pypi) branch.

**Comment by nlamirault** [comment]
Great !

**Comment by proofit404** [comment]
Done.
