### ISSUE TITLE
How to set up python3 environment?

### ISSUE THREAD

**Issue by LQYMGT** [proofit404/company-anaconda#4]
The default python in my system is python2, but I just want to use python3. And I could not make it work...

**Comment by proofit404** [comment]
You can create python 3 virtual environment and set `python-shell-virtualenv-path` to it.  I have plans to simplify this but doesn't have enough time to implement it.

**Comment by LQYMGT** [comment]
Thanks a lot. Maybe you can put the solution to the README :)

**Comment by proofit404** [comment]
Actually I want to use `python-shell-interpreter` value.
