### ISSUE TITLE
Completion - docstring

### ISSUE THREAD

**Issue by silgon** [proofit404/company-anaconda#5]
In the README.md file, you have an image showing that you can be able to see the docstring of a function.

![Example image](https://cloud.githubusercontent.com/assets/901061/7654174/599d57a0-fb1b-11e4-8f2f-14c5d712a8dc.png)

In that image the buffer in which the docstring is displayed is called *anaconda-doc*. I would like to know if there's something extra to do in order to display it, because the auto-completion is working fine, but I cannot see any docstring and it would be nice some times to have it.

Thanks in advance ;)

**Comment by proofit404** [comment]
You should use `company-show-doc-buffer` command with company-mode tooltip active. Default key-bindings are `C-h` and `f1`.
