### ISSUE TITLE
How to  ignore case ?

### ISSUE THREAD

**Issue by hello-code** [proofit404/company-anaconda#6]
How to  ignore case ?

I'm using prelude emacs .

![qq 20150522102629](https://cloud.githubusercontent.com/assets/7741586/7763037/9f625360-006d-11e5-875e-2a770f60691a.png)
![qq 20150522102634](https://cloud.githubusercontent.com/assets/7741586/7763039/a336bf62-006d-11e5-85db-382b7d0dfc7c.png)

I want 'Field',but when I type f I only get fields...

Thanks for your help!

**Comment by proofit404** [comment]
It must works without any tuning. Maybe @dgutov can say something on it?
![autocomplete](https://cloud.githubusercontent.com/assets/1862725/7766477/2e5c487e-0072-11e5-89e1-71195f2bec8a.png)

**Comment by dgutov** [comment]
@hello-code Have you set `completion-ignore-case` to nil in your configuration?

@proofit404 Might there be some code in anaconda-mode that is sensitive to this variable? That would explain the difference.

However, you also need to return `t` to `ignore-case` in the backend (sorry this command hasn't been documented yet). Without it, if you type `o` in the example above, the results should exclude both lowercase options displayed on the screenshot, because the built-in cache uses the value of `ignore-case` from the backend.

**Comment by proofit404** [comment]
Here is my configuration related to `company`:
```lisp
(global-company-mode)

(setq company-idle-delay 0.3)

(setq company-minimum-prefix-length 2)

(setq company-transformers '(company-sort-by-backend-importance))

(setq company-continue-commands '(not helm-dabbrev))

(add-to-list 'company-backends '(company-anaconda :with company-yasnippet))
(add-to-list 'company-backends '(company-tern :with company-yasnippet))
(add-to-list 'company-backends 'company-edbi)
(add-to-list 'company-backends 'company-irony)

(global-set-key (kbd "<C-tab>") 'company-complete)

(define-key company-active-map (kbd "C-n") 'company-select-next)
(define-key company-active-map (kbd "C-p") 'company-select-previous)

(diminish 'company-mode)
```
Seems like `company` itself doesn't handle `ignore-case` properly in some cases.

**Comment by hello-code** [comment]
Seems like company itself doesn't handle ignore-case properly in some cases...

**Comment by dgutov** [comment]
Neither of you have answered the question addressed to each person.

**Comment by hello-code** [comment]
I'm so sorry...
I think I can live with that.

**Comment by proofit404** [comment]
@dgutov Sorry for my inattention. There is no code depending on `ignore-case` behavior of company-mode. Also I push correction commit for missing option. Hope this will fix @hello-code problem.

**Comment by dgutov** [comment]
> There is no code depending on ignore-case behavior of company-mode.

The question was whether there's code depending on `completion-ignore-case`. It seems there isn't, and the screenshot in this report is the result of the completions list being retrieved after the user typed `.`; then when they typed `f`, it was fetched from cache and narrowed down in case-sensitive fashion.
