### ISSUE TITLE
Does not hand over to other backends

### ISSUE THREAD

**Issue by cpaulik** [proofit404/company-anaconda#8]
Hi,

I might be wrong about this but I think that company-anaconda does not hand over to other backends properly.

e.g. I'm using the company backends `company-anaconda` and `company-dabbrev` but `company-dabbrev` never gets to complete.

Shouldn't `company-anaconda` hand over to the next backend if it can not find a completion candidate?

**Comment by proofit404** [comment]
Can you provide full value for `company-backends` variable?

**Comment by cpaulik** [comment]
Yes it is 

```elisp
(company-anaconda
 (company-dabbrev-code company-gtags company-etags company-keywords)
 company-files company-dabbrev)
```

But I've also tried with 
```elisp
(company-anaconda company-dabbrev)
```

A fake code example where `company-dabbrev` works but `company-anaconda` can no work would be 
```python
def pack():
    user.requests.pickupfolder()
    user.requests.picdsdfsf()

    user.requests.|
```

with `|` the cursor position.

**Comment by proofit404** [comment]
Oh. I understand. Does `dabbrev` backend works in strings or comments.
`company-anaconda` always return `t` for `prefix` command (with `anaconda-mode` turned on). But this doesn't guarantee that `candidates` will return some value.

Doesn't think I know how to fix this properly. @dgutov what do you think?

**Comment by proofit404** [comment]
Also try to set `company-backends` to `'((company-anaconda :with company-dabbrev))`

**Comment by dgutov** [comment]
> Shouldn't company-anaconda hand over to the next backend if it can not find a completion candidate?

No.

This question has been asked many times in the company-mode issue tracker already. If you want completions from several sources, try grouping.

**Comment by proofit404** [comment]
@dgutov Excuse for troubling

**Comment by dgutov** [comment]
It's no trouble, just a question repeated too often. I wonder where people get the idea that it should work like that.

The built-in Emacs completion doesn't do that, nor do the popular IDEs, to the best of my knowledge.

**Comment by cpaulik** [comment]
Thanks for the help. I've tried grouping and it is fine.

Regarding the issue where people get this idea. I have two reasons why I thought this was possible:

- `company-backends` is a list. So it would make sense that they are asked one after the other if they can provide completions
- The `company-backends` documentation says:

> ... text immediately before point.  Returning nil from this command passes
> control to the next back-end.  The function should return `stop' if it ...

Which lead me to think that it should be possible to pass control from one backend to the next. 

This also leads to the question: Is there a reason why this could not work?

**Comment by dgutov** [comment]
> So it would make sense that they are asked one after the other if they can provide completions

They're asked *if* they can provide completions one-by-one, not for completions themselves.

> Returning nil from this command passes control to the next back-end.

That's from the description for the `prefix` command. You don't want to compute completions in it, because it can be called several times per command, from different buffer positions.

**Comment by cpaulik** [comment]
Yes I can understand the logic behind it now. But without quite detailed knowledge this question seems reasonable. That's probably why it comes up often.

Anyway thank you again. If nothing can be done about it than I will close this issue.

**Comment by dgutov** [comment]
In my view, the `company-backends` description is quite clear. But hopefully sometime, someone for whom it isn't, will try to clarify it for those who come later.

For instance, by editing http://www.emacswiki.org/emacs/CompanyMode.

**Comment by proofit404** [comment]
@cpaulik Do you try `:with` keyword?

**Comment by cpaulik** [comment]
@proofit404 Yes I tried it and it works partly. But now my anaconda completion candidates are mixed with the ones from company-dabbrev. I would love a feature that sorts the completion candidates by backend because this would pretty much feel like company-anaconda handing over to company-dabbrev if the first on can not complete.

**Comment by cpaulik** [comment]
It seems that this is already on the wishlist https://github.com/company-mode/company-mode/issues/317
